lthrt_contact_address:
    resource: "@LthrtContactBundle/Resources/config/routing/address.yml"
    prefix:   /address

lthrt_contact_addresstype:
    resource: "@LthrtContactBundle/Resources/config/routing/addresstype.yml"
    prefix:   /addresstype

lthrt_contact_city:
    resource: "@LthrtContactBundle/Resources/config/routing/city.yml"
    prefix:   /city

lthrt_contact_contact:
    resource: "@LthrtContactBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

lthrt_contact_contacttype:
    resource: "@LthrtContactBundle/Resources/config/routing/contacttype.yml"
    prefix:   /contacttype

lthrt_contact_county:
    resource: "@LthrtContactBundle/Resources/config/routing/county.yml"
    prefix:   /county

lthrt_contact_city_county_state:
    resource: "@LthrtContactBundle/Resources/config/routing/citycountystate.yml"
    prefix:   /ccs

lthrt_contact_demographic:
    resource: "@LthrtContactBundle/Resources/config/routing/demographic.yml"
    prefix:   /demographic

lthrt_contact_demographictype:
    resource: "@LthrtContactBundle/Resources/config/routing/demographictype.yml"
    prefix:   /demographictype

lthrt_contact_person:
    resource: "@LthrtContactBundle/Resources/config/routing/person.yml"
    prefix:   /person

lthrt_contact_state:
    resource: "@LthrtContactBundle/Resources/config/routing/state.yml"
    prefix:   /state

lthrt_contact_zip:
    resource: "@LthrtContactBundle/Resources/config/routing/zip.yml"
    prefix:   /zip

# lthrt_contact_entity:
#     resource: "@LthrtContactBundle/Resources/config/routing/entity.yml"
#     prefix:   /entity
