<?php

namespace Lthrt\ContactBundle\Repository;

use Lthrt\ContactBundle\Repository\RepositoryTrait\ContactBundleRepository;

/**
 * CityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    use ContactBundleRepository;

    const ROOT = 'city';

    public function findByCounty($abbr)
    {
        $qb = $this->findNames();
        $qb->join(self::ROOT . '.state', StateRepository::ROOT);
        $qb->join(self::ROOT . '.county', CountyRepository::ROOT);
        $qb->andWhere($qb->expr()->eq(CountyRepository::ROOT . '.name', ':name'));
        $qb->setParameter('name', $name);

        return $qb;
    }

    public function findByStateAbbr($abbr)
    {
        $qb = $this->findNames();
        $qb->join(self::ROOT . '.state', StateRepository::ROOT);
        $qb->andWhere($qb->expr()->eq(StateRepository::ROOT . '.abbr', ':abbr'));
        $qb->setParameter('abbr', $abbr);

        return $qb;
    }

    public function findNames()
    {
        $qb = $this->qb();
        $qb->orderBy(self::ROOT . '.name');
        $qb->select(self::ROOT . '.name');
        $qb->distinct();

        return $qb;
    }
}
