<?php

namespace Lthrt\ContactBundle\Repository;

/**
 * DemographicRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemographicRepository extends \Doctrine\ORM\EntityRepository
{
}
