<?php

namespace Lthrt\ContactBundle\Repository;

/**
 * DemographicTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemographicTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
