<?php

namespace Lthrt\ContactBundle\Repository;

/**
 * ZipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipRepository extends \Doctrine\ORM\EntityRepository
{
}
