# Lthrt\ContactBundle\Entity\Contact:
#     type: entity
#     table: contact
#     repositoryClass: Lthrt\ContactBundle\Repository\ContactRepository

#     fields:
#         value:
#             column: value
#             type: string
#             length: 63
#             nullable: false

#     manyToOne:
#         contactType:
#             targetEntity: ContactType
#             joinColumn:
#                 name: contact_type_id

#     lifecycleCallbacks: { }
