Lthrt\ContactBundle\Entity\DemographicType:

    # eg race, ethnicity, gender

    type: entity
    table: demographic_type
    repositoryClass: Lthrt\ContactBundle\Repository\DemographicTypeRepository

    fields:
        name:
            column: name
            type: string
            length: 63
            nullable: false

    lifecycleCallbacks: { }
