city:
    path:     /
    defaults: { _controller: "LthrtContactBundle:City:index" }

city_create:
    path:     /create
    defaults: { _controller: "LthrtContactBundle:City:create" }
    methods:  POST

city_delete:
    path:     /{city}/delete
    defaults: { _controller: "LthrtContactBundle:City:delete" }
    methods:  [POST, DELETE]
    requirements:
        city: \d+

city_edit:
    path:     /{city}/edit
    defaults: { _controller: "LthrtContactBundle:City:edit" }
    requirements:
        city: \d+

city_new:
    path:     /new
    defaults: { _controller: "LthrtContactBundle:City:new" }

city_show:
    path:     /{city}/show
    defaults: { _controller: "LthrtContactBundle:City:show" }
    requirements:
        city: \d+

city_update:
    path:     /{city}/update
    defaults: { _controller: "LthrtContactBundle:City:update" }
    methods:  [POST, PUT]
    requirements:
        city: \d+
