contact:
    path:     /
    defaults: { _controller: "LthrtContactBundle:Contact:index" }

contact_create:
    path:     /create
    defaults: { _controller: "LthrtContactBundle:Contact:create" }
    methods:  POST

contact_delete:
    path:     /{contact}/delete
    defaults: { _controller: "LthrtContactBundle:Contact:delete" }
    methods:  [POST, DELETE]
    requirements:
        contact: \d+

contact_edit:
    path:     /{contact}/edit
    defaults: { _controller: "LthrtContactBundle:Contact:edit" }
    requirements:
        contact: \d+

contact_new:
    path:     /new
    defaults: { _controller: "LthrtContactBundle:Contact:new" }

contact_show:
    path:     /{contact}/show
    defaults: { _controller: "LthrtContactBundle:Contact:show" }
    requirements:
        contact: \d+

contact_update:
    path:     /{contact}/update
    defaults: { _controller: "LthrtContactBundle:Contact:update" }
    methods:  [POST, PUT]
    requirements:
        contact: \d+
