county_by_state_form:
    path:     /state/{state}
    defaults: { _controller: "LthrtContactBundle:CountyState:form" }
    requirements:
        state: \d*

state_by_county_form:
    path:     /county/{county}
    defaults: { _controller: "LthrtContactBundle:CountyState:form" }
    requirements:
        county: \d*

county_state_form:
    path:     /
    defaults: { _controller: "LthrtContactBundle:CountyState:form" }

