county:
    path:     /
    defaults: { _controller: "LthrtContactBundle:County:index" }

county_create:
    path:     /create
    defaults: { _controller: "LthrtContactBundle:County:create" }
    methods:  POST

county_delete:
    path:     /{county}/delete
    defaults: { _controller: "LthrtContactBundle:County:delete" }
    methods:  [POST, DELETE]
    requirements:
        county: \d+

county_edit:
    path:     /{county}/edit
    defaults: { _controller: "LthrtContactBundle:County:edit" }
    requirements:
        county: \d+

county_new:
    path:     /new
    defaults: { _controller: "LthrtContactBundle:County:new" }

county_show:
    path:     /{county}/show
    defaults: { _controller: "LthrtContactBundle:County:show" }
    requirements:
        county: \d+

county_update:
    path:     /{county}/update
    defaults: { _controller: "LthrtContactBundle:County:update" }
    methods:  [POST, PUT]
    requirements:
        county: \d+
